// <auto-generated />
using System;
using DAB.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAB.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514174023_AddCoreDABFeatures")]
    partial class AddCoreDABFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAB.API.Models.Banque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Banques");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = 1001,
                            Email = "contact@banqueparis.fr",
                            Nom = "Banque de Paris",
                            Rue = "10 Avenue Champs",
                            Ville = "Paris"
                        });
                });

            modelBuilder.Entity("DAB.API.Models.CarteBancaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activée")
                        .HasColumnType("bit");

                    b.Property<bool>("Bloquée")
                        .HasColumnType("bit");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("CompteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCréation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LimitRetraitQuotidien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NuméroCartе")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("TotalRetraitAujourd")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompteId");

                    b.ToTable("CartesBancaires");
                });

            modelBuilder.Entity("DAB.API.Models.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BanqueId")
                        .HasColumnType("int");

                    b.Property<string>("CodePIN")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("DabId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCréation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DernièreActivité")
                        .HasColumnType("datetime2");

                    b.Property<int>("Etat")
                        .HasColumnType("int");

                    b.Property<decimal>("LimitRetraitQuotidien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroCompte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Proprietaire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Solde")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StatutSecurité")
                        .HasColumnType("int");

                    b.Property<int>("TentativesÉchouéesConnexion")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalRetraitAujourd")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BanqueId");

                    b.HasIndex("DabId");

                    b.ToTable("Comptes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BanqueId = 1,
                            DabId = 1,
                            DateCréation = new DateTime(2026, 5, 14, 17, 40, 22, 249, DateTimeKind.Utc).AddTicks(6441),
                            Etat = 0,
                            LimitRetraitQuotidien = 1000m,
                            NumeroCompte = "FR1001",
                            Proprietaire = "Alice Dupont",
                            Solde = 5000m,
                            StatutSecurité = 0,
                            TentativesÉchouéesConnexion = 0,
                            TotalRetraitAujourd = 0m,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            BanqueId = 1,
                            DabId = 1,
                            DateCréation = new DateTime(2026, 5, 14, 17, 40, 22, 249, DateTimeKind.Utc).AddTicks(6455),
                            Etat = 0,
                            LimitRetraitQuotidien = 1000m,
                            NumeroCompte = "FR1002",
                            Proprietaire = "Bob Martin",
                            Solde = 150m,
                            StatutSecurité = 0,
                            TentativesÉchouéesConnexion = 0,
                            TotalRetraitAujourd = 0m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("DAB.API.Models.Dab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DABId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dabs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DABId = "DAB-P1",
                            Localisation = "Gare de Lyon"
                        });
                });

            modelBuilder.Entity("DAB.API.Models.Réclamation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateRésolution")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSoumission")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RéponseAdmin")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompteId");

                    b.HasIndex("TransactionId");

                    b.ToTable("Réclamations");
                });

            modelBuilder.Entity("DAB.API.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Catégorie")
                        .HasColumnType("int");

                    b.Property<int>("CompteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("Frais")
                        .HasColumnType("float");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Référence")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.HasIndex("CompteId");

                    b.ToTable("Transactions");

                    b.HasDiscriminator<string>("TransactionType").HasValue("Transaction");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DAB.API.Models.TransactionRetrait", b =>
                {
                    b.HasBaseType("DAB.API.Models.Transaction");

                    b.Property<bool>("AutreAgence")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Retrait");
                });

            modelBuilder.Entity("DAB.API.Models.TransactionTransfert", b =>
                {
                    b.HasBaseType("DAB.API.Models.Transaction");

                    b.Property<string>("NumeroCompteDestination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Transfert");
                });

            modelBuilder.Entity("DAB.API.Models.CarteBancaire", b =>
                {
                    b.HasOne("DAB.API.Models.Compte", "Compte")
                        .WithMany("CartesBancaires")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("DAB.API.Models.Compte", b =>
                {
                    b.HasOne("DAB.API.Models.Banque", "Banque")
                        .WithMany("Comptes")
                        .HasForeignKey("BanqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAB.API.Models.Dab", "Dab")
                        .WithMany("Comptes")
                        .HasForeignKey("DabId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Banque");

                    b.Navigation("Dab");
                });

            modelBuilder.Entity("DAB.API.Models.Réclamation", b =>
                {
                    b.HasOne("DAB.API.Models.Compte", "Compte")
                        .WithMany("Réclamations")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAB.API.Models.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Compte");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("DAB.API.Models.Transaction", b =>
                {
                    b.HasOne("DAB.API.Models.Compte", "Compte")
                        .WithMany("Transactions")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("DAB.API.Models.Banque", b =>
                {
                    b.Navigation("Comptes");
                });

            modelBuilder.Entity("DAB.API.Models.Compte", b =>
                {
                    b.Navigation("CartesBancaires");

                    b.Navigation("Réclamations");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DAB.API.Models.Dab", b =>
                {
                    b.Navigation("Comptes");
                });
#pragma warning restore 612, 618
        }
    }
}
